name: Run Behave Tests and Send CTRF CSV Report via Email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}

jobs:
  behave-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave allure-behave
          python -m playwright install --with-deps

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Behave tests with HTML and JSON output
        run: |
          behave -f behave_html_formatter:HTMLFormatter -o reports/reports.html \
                 -f json -o behave_raw.json

      - name: Convert Behave JSON to CTRF JSON
        run: |
          python pages/convert_to_ctrf.py

      - name: Convert CTRF JSON to CSV
        run: |
          python pages/convert_ctrf_to_csv.py

      - name: Email CTRF Report (CSV Format)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "✅ TouchTight Test Report"
          body: |
            Hello,

            The latest test results are attached as a CSV file (Excel-compatible).

            Regards,  
            QA Automation Team
          to: testns0222@gmail.com
          from: QA <${{ secrets.EMAIL_USER }}>
          attachments: Test_Report.csv
