name: Run Behave Tests with Allure, Publish Report & Send Email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  behave-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Behave tests
        run: behave

      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOUCHTIGHT_TOKEN_GITHUB }}
          publish_dir: ./allure-report

      - name: Send Email with Report Link
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "✅ Allure Report - GitHub Actions"
          body: |
            Hello,

            The latest Allure test report is available at:
            https://nasirshahzadyasin.github.io/touchtight-automation-1/

            Regards,  
            GitHub CI
          to: testns0222@gmail.com
          from: GitHub CI <${{ secrets.EMAIL_USER }}>
